### ISSUE TITLE
Null Pointer Exception if card has to be drawn from pile

### ISSUE THREAD

**Issue by cyrill10** [chrisrayrayne/uno#43]
`Exception in thread "main" java.lang.NullPointerException
	at ch.chrisrayrayne.Game.play(Game.java:167)
	at ch.chrisrayrayne.Uno.main(Uno.java:12)`

Wenn keine Karte gelegt werden kann wird Null statt eine "Card" zurück gegeben, sodass ein Nullpointer resultiert.

**Comment by chrisrayrayne** [comment]
Gemacht
